name: Release

on:
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: 'Person to greet'
    #     required: true
    #     default: 'Mona the Octocat'
    #   home:
    #     description: 'location'
    #     required: false
    #     default: 'The Octoverse'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo release
